<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="39382" started-at="2023-02-20T19:55:11 IST" finished-at="2023-02-20T19:55:50 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="39382" started-at="2023-02-20T19:55:11 IST" finished-at="2023-02-20T19:55:50 IST">
      <class name="testScript.FirstTest">
        <test-method status="PASS" signature="classConfiguration()[pri:0, instance:testScript.FirstTest@74a10858]" name="classConfiguration" is-config="true" duration-ms="3646" started-at="2023-02-20T19:55:11 IST" finished-at="2023-02-20T19:55:14 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classConfiguration -->
        <test-method status="PASS" signature="methodConfiguration()[pri:0, instance:testScript.FirstTest@74a10858]" name="methodConfiguration" is-config="true" duration-ms="23083" started-at="2023-02-20T19:55:14 IST" finished-at="2023-02-20T19:55:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodConfiguration -->
        <test-method status="FAIL" signature="firstTest()[pri:0, instance:testScript.FirstTest@74a10858]" name="firstTest" duration-ms="10808" started-at="2023-02-20T19:55:37 IST" finished-at="2023-02-20T19:55:48 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Selenium Training] but found [[[ChromeDriver: chrome on WINDOWS (cf4f73d7ac1137c8cc341d6cacc7fae9)] -> xpath: //h1[@class='page-header']]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Selenium Training] but found [[[ChromeDriver: chrome on WINDOWS (cf4f73d7ac1137c8cc341d6cacc7fae9)] -> xpath: //h1[@class='page-header']]]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testScript.FirstTest.firstTest(FirstTest.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstTest -->
        <test-method status="PASS" signature="methodTearDown()[pri:0, instance:testScript.FirstTest@74a10858]" name="methodTearDown" is-config="true" duration-ms="1689" started-at="2023-02-20T19:55:48 IST" finished-at="2023-02-20T19:55:50 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodTearDown -->
        <test-method status="PASS" signature="classTearDown()[pri:0, instance:testScript.FirstTest@74a10858]" name="classTearDown" is-config="true" duration-ms="2" started-at="2023-02-20T19:55:50 IST" finished-at="2023-02-20T19:55:50 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classTearDown -->
      </class> <!-- testScript.FirstTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
